const fs = require('fs');
let c = fs.readFileSync('DACS/data/admin_head.tsx', 'utf8');

const fixes = [
  ['g?n', 'gần'],
  ['nh?t', 'nhất'],
  ['g?n nh?t', 'gần nhất'],
  ['ngày g?n nh?t', 'ngày gần nhất'],
  ['ngày g?n', 'ngày gần'],
  // Fix other literal ? patterns
  ['h\u00eem', 'hôm'],
  ['C?p nh?t', 'Cập nhật'],
  ['S? s?n', 'Số sản'],
  ['t?t c?', 'tất cả'],
  ['C?p nh?t l?i', 'Cập nhật lại'],
  ['C?p nh?t thành', 'Cập nhật thành'],
  ['Thm thnh', 'Thêm thành'],
  ['l?u s?n', 'lưu sản'],
  ['Thm s?n', 'Thêm sản'],
  ['Thm bn', 'Thêm bàn'],
  ['d?y d?', 'đầy đủ'],
  ['l?i ton', 'lại toàn'],
  ['T?o t?ng', 'Tạo từng'],
  ['m?i', 'mới'],
  ['d?i', 'đổi'],
  ['d? thay', 'đã thay'],
  ['d? c', 'đã c'],
  ['d? g?', 'đã gửi'],
  ['d? hon', 'đã hoàn'],
  ['?nh t?i', 'ảnh tại'],
  ['Vui lng', 'Vui lòng'],
  ['Nh?p d?y', 'Nhập đầy'],
  ['Khng', 'Không'],
  ['ch?i', 'chủ'],
  ['? nu?ng', 'Đồ nướng'],
  ['Chua c', 'Chưa có'],
  ['Ch?n', 'Chọn'],
  ['H?y', 'Hủy'],
  ['Qu?n', 'Quản'],
  ['Luu', 'Lưu'],
  ['B?t', 'Bật'],
  ['Xc', 'Xác'],
  ['Tn', 'Tên'],
  ['th m ti', 'thêm tài'],
  ['Hnh d?ng', 'Hành động'],
  ['M?t kh?u', 'Mật khẩu'],
  ['di?n tho?i', 'điện thoại'],
  ['B?o m?t', 'Bảo mật'],
  ['ti kho?n', 'tài khoản'],
  ['nhn vin', 'nhân viên'],
  ['ang g?', 'Đang gửi'],
  ['d?y d?', 'đầy đủ'],
  ['tru?c khi', 'trước khi'],
  ['c?u hnh', 'cấu hình'],
  ['ang nh?p', 'Đang nhập'],
  ['Xc nh?n', 'Xác nhận'],
  ['v xc th?c', 'và xác thực'],
  ['2 l?p', '2 lớp'],
  ['khng', 'không'],
  ['? tr?ng', 'Để trống'],
  ['b?t bu?c', 'bắt buộc'],
  ['Khuyn ngh?', 'Khuyến nghị'],
  ['sau khi', 'sau khi'],
  ['Theo di', 'Theo dõi'],
  ['vai trò', 'vai trò'],
  ['Hi?n t?i', 'Hiện tại'],
  ['ch? c', 'chỉ có'],
  ['B?n c?n', 'Bạn cần'],
  ['quy?n', 'quyền'],
  ['d? truy', 'để truy'],
  ['Truy c?p', 'Truy cập'],
  ['dang nh?p', 'đăng nhập'],
  ['th? t?i', 'thử tới'],
  ['th email', 'thử email'],
  ['G?i th?', 'Gửi thử'],
  ['ang b?t', 'Đang bật'],
  ['ang t?t', 'Đang tắt'],
  ['Ho?t d?ng', 'Hoạt động'],
  ['T?m kho', 'Tạm khóa'],
  ['Xa', 'Xóa'],
  ['Ch? c?n', 'Chỉ cần'],
  ['Luu thay', 'Lưu thay'],
  ['Luu b?o', 'Lưu bảo'],
  ['Luu email', 'Lưu email'],
  ['thêm/ xóa', 'thêm/xóa'],
  ['C?p nh?t QR', 'Cập nhật QR'],
  ['Nh?p tr?c', 'Nhập trực'],
  ['h?m nay', 'hôm nay'],
  ['Kho', 'Kho'],
  ['??', '📊'],
  ['Bi?u d?', 'Biểu đồ'],
];

let count = 0;
for (const [old, neo] of fixes) {
  if (c.includes(old)) {
    c = c.split(old).join(neo);
    count++;
    console.log('Fixed:', old, '->', neo);
  }
}

fs.writeFileSync('DACS/data/admin_head.tsx', c, 'utf8');
console.log('\nTotal fixes:', count);
